version: "3.4"

services:
  app:
    image: node:14
    container_name: boilerplate
    command: >
      bash -c "cd /app && yarn && yarn start:debug"
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/